module.exports = { browse, searchLogs, fillInGeneralNeedsLettingsLog, login, fillInSupportedHousingLettingsLog }

// All functions here have been generated with playwright codegen, and edited to use variables as needed

async function login(page, userContext) {
    await page.goto(userContext.vars.target);
    await page.getByRole('button', { name: 'Start now' }).click();
    await page.getByLabel('Email address').click();
    await page.getByLabel('Email address').fill(userContext.vars.username);
    await page.getByLabel('Password').click();
    await page.getByLabel('Password').fill(userContext.vars.password);
    await page.getByRole('button', { name: 'Sign in' }).click();
}

async function browse(page, userContext) {
    await login(page, userContext);
    await page.getByRole('link', { name: 'Sales logs' }).click();
    await page.getByRole('link', { name: 'About your organisation' }).click();
    await page.getByRole('link', { name: 'View agreement' }).click();
    await page.getByRole('link', { name: 'Stock owners' }).click();
    await page.getByRole('link', { name: 'Managing agents' }).click();
    await page.getByRole('link', { name: 'Schemes' }).click();
    await page.getByRole('link', { name: 'Lettings logs' }).click();
    await page.getByRole('link', { name: 'Log' }).first().click();
    await page.getByRole('link', { name: 'Set up this lettings log' }).click();
    await page.getByRole('link', { name: 'Lettings logs' }).click();
    await page.locator('li').filter({ hasText: 'Sign out' }).click();
}

async function searchLogs(page, userContext) {
    await login(page, userContext);
    await page.getByLabel('Search by log ID, tenant code, property reference or postcode').click();
    await page.getByLabel('Search by log ID, tenant code, property reference or postcode').fill('NW5 1TL');
    await page.getByLabel('Search by log ID, tenant code, property reference or postcode').press('Enter');
    await page.getByLabel('Search by log ID, tenant code, property reference or postcode').click();
    await page.getByLabel('Search by log ID, tenant code, property reference or postcode').fill('42');
    await page.getByLabel('Search by log ID, tenant code, property reference or postcode').press('Enter');
    await page.getByLabel('Search by log ID, tenant code, property reference or postcode').click();
    await page.getByLabel('Completed').check();
    await page.getByLabel('Search by log ID, tenant code, property reference or postcode').click();
    await page.getByLabel('Search by log ID, tenant code, property reference or postcode').fill('');
    await page.getByLabel('Search by log ID, tenant code, property reference or postcode').press('Enter');
    await page.getByLabel('Completed').check();
    await page.getByRole('button', { name: 'Apply filters' }).click();
    await page.getByLabel('Completed').uncheck();
    await page.getByLabel('In progress').check();
    await page.getByRole('button', { name: 'Apply filters' }).click();
    await page.getByLabel('in progress').uncheck();
    await page.getByRole('button', { name: 'Apply filters' }).click();
    await page.getByLabel('Search by log ID, tenant code, property reference or postcode').click();
    await page.getByLabel('Search by log ID, tenant code, property reference or postcode').fill(`${userContext.vars.logReference}`);
    await page.getByLabel('Search by log ID, tenant code, property reference or postcode').press('Enter');
    await page.getByRole('link', { name: 'Log' }).first().click();
    await page.locator('li').filter({ hasText: 'Sign out' }).click();
}

async function fillInGeneralNeedsLettingsLog(page, userContext) {
    await login(page, userContext);
    await page.getByRole('button', { name: 'Create a new lettings log' }).click();
    await page.getByRole('link', { name: 'Set up this lettings log' }).click();
    if (userContext.vars.hasOrgRelationships) {
        await page.getByRole('button', { name: 'Save and continue' }).click();
        await page.getByRole('button', { name: 'Save and continue' }).click();
    }
    await page.getByLabel('General needs').check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('No').check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('Day').click();
    await page.getByLabel('Day').fill('19');
    await page.getByLabel('Month').click();
    await page.getByLabel('Month').fill('10');
    await page.getByLabel('Year').click();
    await page.getByLabel('Year').fill('2023');
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('Affordable Rent', { exact: true }).check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('Set up this lettings logQ7 - What is the tenant code?').click();
    await page.getByLabel('Set up this lettings logQ7 - What is the tenant code?').fill(`Test-${Math.floor(Math.random() * 10000000)}`);
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('Set up this lettings logQ8 - What is the property reference?').click();
    await page.getByLabel('Set up this lettings logQ8 - What is the property reference?').fill(`Test-${Math.floor(Math.random() * 10000000)}`);
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByRole('button', { name: 'Save and go to next incomplete section' }).click();
    await page.getByLabel('No').check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('Address line 1').click();
    await page.getByLabel('Address line 1').fill('Highgate Studios');
    await page.getByLabel('Town or city').click();
    await page.getByLabel('Town or city').fill('London');
    await page.getByLabel('Postcode').click();
    await page.getByLabel('Postcode').fill('NW5 1TL');
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('Yes').check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('First let of conversion, rehabilitation or acquired property').check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('Property informationQ18 - How many times was the property offered between becoming vacant and this letting?').click();
    await page.getByLabel('Property informationQ18 - How many times was the property offered between becoming vacant and this letting?').fill('0');
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('Flat or maisonette', { exact: true }).check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('Converted from previous residential or non-residential property').check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('Yes').check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('Property informationQ22 - How many bedrooms does the property have?').click();
    await page.getByLabel('Property informationQ22 - How many bedrooms does the property have?').fill('2');
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('Day').click();
    await page.getByLabel('Day').fill('10');
    await page.getByLabel('Month').click();
    await page.getByLabel('Month').fill('10');
    await page.getByLabel('Year').click();
    await page.getByLabel('Year').fill('2023');
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByRole('button', { name: 'Save and go to next incomplete section' }).click();
    await page.getByLabel('No', { exact: true }).check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('No').check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('Assured Shorthold Tenancy (AST) – Fixed term').check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('Tenancy informationQ28 - What is the length of the fixed-term tenancy to the nearest year?').click();
    await page.getByLabel('Tenancy informationQ28 - What is the length of the fixed-term tenancy to the nearest year?').fill('3');
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByRole('button', { name: 'Save and go to next incomplete section' }).click();
    await page.getByLabel('The tenant has seen the DLUHC privacy notice').check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('Household characteristicsQ31 - How many people live in the household for this letting?').click();
    await page.getByLabel('Household characteristicsQ31 - How many people live in the household for this letting?').fill('2');
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('Yes').check();
    await page.getByLabel('Age').click();
    await page.getByLabel('Age').fill('30');
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('Female').check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('White').check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('English, Welsh, Northern Irish, Scottish or British').check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('United Kingdom').check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('Not seeking work').check();
    await page.getByLabel('Part-time – Less than 30 hours').check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('Yes').check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('Child').check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('Yes').check();
    await page.getByLabel('Age').click();
    await page.getByLabel('Age').fill('1');
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('Female').check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByRole('button', { name: 'Save and go to next incomplete section' }).click();
    await page.getByText('No', { exact: true }).click();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('No', { exact: true }).check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('Yes').check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('None of the listed options').check();
    await page.getByLabel('Fully wheelchair accessible housing').check();
    await page.getByLabel('No', { exact: true }).check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('Yes').check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('Mobility').check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByRole('button', { name: 'Save and go to next incomplete section' }).click();
    await page.getByText('1 year but under 2 years').click();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByText('Less than 1 year').click();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByText('Relationship breakdown (non-violent) with partner').click();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.locator('div').filter({ hasText: /^Living with friends or family$/ }).click();
    await page.getByLabel('Living with friends or family').check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('No').check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('No').check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('Yes').check();
    await page.getByLabel('Select a local authority').click();
    await page.getByLabel('Select a local authority').fill('Camd');
    await page.getByRole('option', { name: 'Camden' }).click();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('Yes').check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('They needed to move due to medical and welfare reasons (including disability)').check();
    await page.getByLabel('They needed to move to avoid hardship to themselves or others').check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByText('Choice-based lettings (CBL) Common Allocation Policy (CAP) Common housing regist').click();
    await page.getByLabel('Choice-based lettings (CBL)').check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('Health service').check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByRole('button', { name: 'Save and go to next incomplete section' }).click();
    await page.getByLabel('No', { exact: true }).check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('Universal Credit housing element').check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('Some').check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('Every calendar month').check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('Q95 - What is the basic rent?').click();
    await page.getByLabel('Q95 - What is the basic rent?').fill('750');
    await page.getByLabel('Q96 - What is the service charge?').click();
    await page.getByLabel('Q96 - What is the service charge?').fill('80');
    await page.getByLabel('Q97 - What is the personal service charge?').click();
    await page.getByLabel('Q97 - What is the personal service charge?').fill('30');
    await page.getByLabel('Q98 - What is the support charge?').click();
    await page.getByLabel('Q98 - What is the support charge?').fill('0');
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('Don’t know').check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByRole('button', { name: 'Save and return to log' }).click();
    await page.getByRole('button', { name: 'Back to lettings logs' }).click();
    await page.locator('li').filter({ hasText: 'Sign out' }).click();
}

async function fillInSupportedHousingLettingsLog(page, userContext) {
    await login(page, userContext);
    await page.getByRole('button', { name: 'Create a new lettings log' }).click();
    await page.getByRole('link', { name: 'Set up this lettings log' }).click();
    if (userContext.vars.hasOrgRelationships) {
        await page.getByRole('button', { name: 'Save and continue' }).click();
        await page.getByRole('button', { name: 'Save and continue' }).click();
    }
    await page.getByLabel('Supported housing').check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('Q9 - What scheme is this log for?').click();
    await page.getByLabel('Q9 - What scheme is this log for?').fill(userContext.vars.schemeSearchTerm);
    await page.getByRole('option').click();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('No').check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('Day').click();
    await page.getByLabel('Day').fill('27');
    await page.getByLabel('Month').click();
    await page.getByLabel('Month').fill('10');
    await page.getByLabel('Year').click();
    await page.getByLabel('Year').fill('2023');
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('Social Rent').check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('Set up this lettings logQ7 - What is the tenant code?').click();
    await page.getByLabel('Set up this lettings logQ7 - What is the tenant code?').fill(`Test-${Math.floor(Math.random() * 10000000)}`);
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('Set up this lettings logQ8 - What is the property reference?').click();
    await page.getByLabel('Set up this lettings logQ8 - What is the property reference?').fill(`Test-${Math.floor(Math.random() * 10000000)}`);
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByRole('button', { name: 'Save and go to next incomplete section' }).click();
    await page.getByLabel('No').check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('Social rent basis').check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('Tenant moved to care home').check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('Property informationQ18 - How many times was the property offered between becoming vacant and this letting?').click();
    await page.getByLabel('Property informationQ18 - How many times was the property offered between becoming vacant and this letting?').fill('1');
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('Day').click();
    await page.getByLabel('Day').fill('26');
    await page.getByLabel('Month').click();
    await page.getByLabel('Month').fill('10');
    await page.getByLabel('Year').click();
    await page.getByLabel('Year').fill('2023');
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('No').check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByRole('button', { name: 'Save and go to next incomplete section' }).click();
    await page.getByLabel('No', { exact: true }).check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('No').check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('Assured Shorthold Tenancy (AST) – Fixed term').check();
    await page.getByLabel('Secure – fixed term').check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('Tenancy informationQ28 - What is the length of the fixed-term tenancy to the nearest year?').click();
    await page.getByLabel('Tenancy informationQ28 - What is the length of the fixed-term tenancy to the nearest year?').fill('5');
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('Don’t know').check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByRole('button', { name: 'Save and go to next incomplete section' }).click();
    await page.getByLabel('The tenant has seen the DLUHC privacy notice').check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('Household characteristicsQ31 - How many people live in the household for this letting?').click();
    await page.getByLabel('Household characteristicsQ31 - How many people live in the household for this letting?').fill('1');
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('Yes').check();
    await page.getByLabel('Yes').press('1');
    await page.getByLabel('Yes').press('9');
    await page.getByLabel('Age').click();
    await page.getByLabel('Age').fill('19');
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('Male', { exact: true }).check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('Tenant prefers not to say').check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('United Kingdom').check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('Full-time student').check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByRole('button', { name: 'Save and go to next incomplete section' }).click();
    await page.getByLabel('No', { exact: true }).check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('Yes').check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByRole('link', { name: 'Change anybody in household pregnant' }).click();
    await page.getByLabel('No', { exact: true }).check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByRole('button', { name: 'Confirm and continue' }).click();
    await page.getByLabel('No', { exact: true }).check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('No', { exact: true }).check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByRole('button', { name: 'Save and go to next incomplete section' }).click();
    await page.getByLabel('5 years or more').check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('1 year but under 2 years').check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('Asked to leave by family or friends').check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('Living with friends or family').check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('Assessed by a local authority as homeless').check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('No').check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('No').check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('Don’t know').check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('None of these allocation systems').check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('Police, probation or prison').check();
    await page.getByLabel('Voluntary agency').check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByRole('button', { name: 'Save and go to next incomplete section' }).click();
    await page.getByLabel('No', { exact: true }).check();
    await page.getByLabel('No', { exact: true }).click();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('Tenant prefers not to say').check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('Don’t know').check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('Yes').check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('Every calendar month').check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('Yes').check();
    await page.getByLabel('No').check();
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('Q95 - What is the basic rent?').click();
    await page.getByLabel('Q95 - What is the basic rent?').fill('600');
    await page.getByLabel('Q96 - What is the service charge?').click();
    await page.getByLabel('Q96 - What is the service charge?').fill('50');
    await page.locator('#scharge_div').getByText('£').click();
    await page.getByLabel('Q96 - What is the service charge?').click();
    await page.getByLabel('Q96 - What is the service charge?').fill('100');
    await page.getByLabel('Q97 - What is the personal service charge?').click();
    await page.getByLabel('Q97 - What is the personal service charge?').fill('50');
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByLabel('Q98 - What is the support charge?').click();
    await page.getByLabel('Q98 - What is the support charge?').fill('0');
    await page.getByRole('button', { name: 'Save and continue' }).click();
    await page.getByRole('button', { name: 'Save and return to log' }).click();
    await page.getByRole('button', { name: 'Back to lettings logs' }).click();
    await page.getByRole('link', { name: 'Sign out' }).click();
}