name: "Create Review App infra"

on:
  workflow_call:
    inputs:
      key:
        required: true
        type: string
      app_repo_role:
        required: true
        type: string

concurrency:
  group: review-app-infra-${{ inputs.key }}
  cancel-in-progress: false

env:
  aws_region: eu-west-2

jobs:
  deploy:
    name: Create infra
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: communitiesuk/submit-social-housing-lettings-and-sales-data-infrastructure
          ref: main

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.aws_region }}
          role-to-assume: ${{ inputs.app_repo_role }}

      - name: Terraform apply
        working-directory: terraform/development/per_review_app
        env:
          workspace: ${{ inputs.key }}
        run: |
          terraform init
          terraform workspace select -or-create $workspace
          terraform apply -auto-approve
