name: "Terraform checks"

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - "main"
      - "dev"

jobs:
  tf_fmt:
    name: tf format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.2
      - name: Check formatting of all terraform files
        run: terraform fmt -check -recursive
  tf_validate:
    name: tf validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.2
      - name: Terraform validate
        run: terraform validate
  tflint:
    name: tflint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache plugin directory
        uses: actions/cache@v3
        with:
          path: ~/.tflint.d/plugins
          key: ubuntu-latest-tflint-${{ hashFiles('.tflint.hcl') }}
      - name: Set up tflint
        uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: v0.47.0
      - name: Init tflint
        run: tflint --init
        env:
          # TODO - consider setting up token on a dedicated github account? see https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/plugins.md#avoiding-rate-limiting for more info about avoiding rate limiting
          GITHUB_TOKEN: ${{ github.token }}
      - name: Run tflint
        run: tflint -f compact --recursive --color
  tfsec:
    name: tfsec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: terraform/
          version: v1.28.1
          # TODO - consider setting up token on a dedicated github account? see https://github.com/marketplace/actions/tfsec-action for more info
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # TODO - consider including values from a tfvars file once we have these? see https://github.com/aquasecurity/tfsec
  checkov:
    name: checkov
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run checkov
        uses: bridgecrewio/checkov-action@v12.2425.0
        with:
          output_format: cli
          quiet: true # display only failed checks
          framework: terraform
          download_external_modules: true
