name: "Terrafrom checks"
on:
  push:
    branches:
      - "main"

jobs:
  tf_fmt:
    name: Check Terraform formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.2
      - name: Check formatting of all terraform files
        run: terraform fmt -check -diff -recursive
  tf_validate:
    name: Check Terraform validity
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.2
      - name: Terraform validate
        run: terraform validate
  tflint:
    name: Run Terraform lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache plugin directory
        uses: actions/cache@v3
        with:
          path: ~/.tflint.d/plugins
          key: ubuntu-latest-tflint-${{ hashFiles('.tflint.hcl') }}
      - name: Set up tflint
        uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: v0.47.0
      - name: Init tflint
        run: tflint --init
        env:
          # TODO - setup a token?
          GITHUB_TOKEN: ${{ github.token }}
      - name: Run tflint
        run: tflint -f compact --recursive
  tfsec:
    name: Run Terraform security static analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: terraform/
          # TODO - setup a token?
          github_token: ${{ secrets.GITHUB_TOKEN }}
  checkov:
    name: Check Terraform configuration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run checkov
        uses: bridgecrewio/checkov-action@v12.1347.0
        with:
          output_format: cli
          quiet: true # display only failed checks
          framework: terraform
